import type { Agent, Cronjob, Approval, Run, AuditEntry, Connector, WorkflowTemplate, Notification } from '@/types'

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'PR Triage Bot',
    type: 'system',
    module: 'projects',
    status: 'active',
    capabilities: ['code-review', 'labeling', 'assignment'],
    memoryScope: 'org/engineering',
    connectors: ['github', 'slack'],
    lastActive: '2026-02-21T10:30:00Z',
    runsCompleted: 1247,
  },
  {
    id: 'agent-2',
    name: 'Content Strategist',
    type: 'system',
    module: 'content',
    status: 'active',
    capabilities: ['outline-generation', 'seo-analysis', 'scheduling'],
    memoryScope: 'org/marketing',
    connectors: ['wordpress', 'google-analytics'],
    lastActive: '2026-02-21T09:15:00Z',
    runsCompleted: 432,
  },
  {
    id: 'agent-3',
    name: 'Finance Auditor',
    type: 'system',
    module: 'finance',
    status: 'idle',
    capabilities: ['categorization', 'anomaly-detection', 'reconciliation'],
    memoryScope: 'org/finance',
    connectors: ['plaid', 'quickbooks'],
    lastActive: '2026-02-20T23:00:00Z',
    runsCompleted: 89,
  },
  {
    id: 'agent-4',
    name: 'Training Coach',
    type: 'user',
    module: 'health',
    status: 'active',
    capabilities: ['plan-generation', 'load-balancing', 'nutrition'],
    memoryScope: 'user/personal',
    connectors: ['garmin', 'google-calendar'],
    lastActive: '2026-02-21T06:00:00Z',
    runsCompleted: 156,
  },
  {
    id: 'agent-5',
    name: 'Release Orchestrator',
    type: 'system',
    module: 'projects',
    status: 'active',
    capabilities: ['versioning', 'changelog', 'deployment'],
    memoryScope: 'org/engineering',
    connectors: ['github', 'vercel', 'slack'],
    lastActive: '2026-02-21T11:00:00Z',
    runsCompleted: 312,
  },
  {
    id: 'agent-6',
    name: 'Expense Tracker',
    type: 'user',
    module: 'finance',
    status: 'error',
    capabilities: ['receipt-scanning', 'categorization', 'reporting'],
    memoryScope: 'user/personal',
    connectors: ['plaid'],
    lastActive: '2026-02-19T14:00:00Z',
    runsCompleted: 67,
  },
]

export const mockCronjobs: Cronjob[] = [
  {
    id: 'cron-1',
    name: 'Nightly PR Triage',
    description: 'Auto-triage and label incoming PRs based on file changes and team ownership',
    schedule: '0 2 * * *',
    module: 'projects',
    automationLevel: 'approval-required',
    status: 'active',
    nextRun: '2026-02-22T02:00:00Z',
    lastRun: '2026-02-21T02:00:00Z',
    lastOutcome: 'success',
    agentId: 'agent-1',
    constraints: { maxActions: 50, allowedTools: ['github-api', 'slack-notify'], requireApproval: true },
    runsCount: 87,
  },
  {
    id: 'cron-2',
    name: 'Weekly Content Digest',
    description: 'Generate content performance report and suggest next week topics',
    schedule: '0 9 * * 1',
    module: 'content',
    automationLevel: 'suggest-only',
    status: 'active',
    nextRun: '2026-02-23T09:00:00Z',
    lastRun: '2026-02-16T09:00:00Z',
    lastOutcome: 'success',
    agentId: 'agent-2',
    constraints: { maxActions: 10, allowedTools: ['analytics-read', 'cms-read'], requireApproval: false },
    runsCount: 12,
  },
  {
    id: 'cron-3',
    name: 'Monthly Financial Close',
    description: 'Reconcile accounts, flag anomalies, and prepare close workspace',
    schedule: '0 0 1 * *',
    module: 'finance',
    automationLevel: 'approval-required',
    status: 'active',
    nextRun: '2026-03-01T00:00:00Z',
    lastRun: '2026-02-01T00:00:00Z',
    lastOutcome: 'success',
    agentId: 'agent-3',
    constraints: { maxActions: 200, spendLimit: 0, allowedTools: ['ledger-write', 'report-generate'], requireApproval: true },
    runsCount: 6,
  },
  {
    id: 'cron-4',
    name: 'Daily Training Sync',
    description: 'Sync training data from wearables and adjust weekly plan',
    schedule: '0 7 * * *',
    module: 'health',
    automationLevel: 'bounded-autopilot',
    status: 'active',
    nextRun: '2026-02-22T07:00:00Z',
    lastRun: '2026-02-21T07:00:00Z',
    lastOutcome: 'success',
    agentId: 'agent-4',
    constraints: { maxActions: 5, allowedTools: ['calendar-write', 'plan-update'], requireApproval: false },
    runsCount: 45,
  },
  {
    id: 'cron-5',
    name: 'Release Pipeline',
    description: 'Automated release candidate build, changelog, and deployment',
    schedule: '0 14 * * 5',
    module: 'projects',
    automationLevel: 'conditional-auto',
    status: 'paused',
    nextRun: '2026-02-27T14:00:00Z',
    lastRun: '2026-02-14T14:00:00Z',
    lastOutcome: 'failure',
    agentId: 'agent-5',
    constraints: { maxActions: 30, allowedTools: ['git', 'ci-trigger', 'slack-notify'], requireApproval: true },
    runsCount: 8,
  },
]

export const mockApprovals: Approval[] = [
  {
    id: 'appr-1',
    title: 'PR #1234: Merge feature/auth-refactor',
    description: 'Agent recommends merging after passing all CI checks and 2 approvals',
    module: 'projects',
    agentName: 'PR Triage Bot',
    cronjobId: 'cron-1',
    status: 'pending',
    priority: 'high',
    createdAt: '2026-02-21T02:15:00Z',
    slaDeadline: '2026-02-21T14:15:00Z',
    diffs: [
      { type: 'modified', path: 'src/auth/provider.ts', before: 'const token = getToken()', after: 'const token = await getSecureToken()' },
    ],
  },
  {
    id: 'appr-2',
    title: 'Publish blog post: "AI Agents in 2026"',
    description: 'Content agent completed final draft with SEO optimizations',
    module: 'content',
    agentName: 'Content Strategist',
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-02-20T16:00:00Z',
    slaDeadline: '2026-02-22T16:00:00Z',
  },
  {
    id: 'appr-3',
    title: 'Recategorize 23 transactions',
    description: 'Finance agent detected miscategorized expenses from vendor "CloudServ Inc"',
    module: 'finance',
    agentName: 'Finance Auditor',
    cronjobId: 'cron-3',
    status: 'pending',
    priority: 'critical',
    createdAt: '2026-02-21T00:30:00Z',
    slaDeadline: '2026-02-21T12:30:00Z',
  },
  {
    id: 'appr-4',
    title: 'Adjust training load: reduce volume 15%',
    description: 'Recovery metrics indicate elevated fatigue; agent suggests deload',
    module: 'health',
    agentName: 'Training Coach',
    status: 'pending',
    priority: 'low',
    createdAt: '2026-02-21T07:15:00Z',
    slaDeadline: '2026-02-23T07:15:00Z',
  },
]

export const mockRuns: Run[] = [
  {
    id: 'run-1',
    cronjobId: 'cron-1',
    cronjobName: 'Nightly PR Triage',
    module: 'projects',
    status: 'completed',
    startedAt: '2026-02-21T02:00:00Z',
    completedAt: '2026-02-21T02:12:00Z',
    duration: 720,
    actionsCount: 14,
    agentName: 'PR Triage Bot',
    artifacts: [
      { id: 'art-1', name: 'triage-report.json', type: 'report', size: 4200, createdAt: '2026-02-21T02:12:00Z' },
      { id: 'art-2', name: 'label-changes.diff', type: 'diff', size: 1800, createdAt: '2026-02-21T02:12:00Z' },
    ],
  },
  {
    id: 'run-2',
    cronjobId: 'cron-4',
    cronjobName: 'Daily Training Sync',
    module: 'health',
    status: 'completed',
    startedAt: '2026-02-21T07:00:00Z',
    completedAt: '2026-02-21T07:03:00Z',
    duration: 180,
    actionsCount: 3,
    agentName: 'Training Coach',
    artifacts: [
      { id: 'art-3', name: 'sync-log.json', type: 'log', size: 2100, createdAt: '2026-02-21T07:03:00Z' },
    ],
  },
  {
    id: 'run-3',
    cronjobId: 'cron-5',
    cronjobName: 'Release Pipeline',
    module: 'projects',
    status: 'failed',
    startedAt: '2026-02-14T14:00:00Z',
    completedAt: '2026-02-14T14:08:00Z',
    duration: 480,
    actionsCount: 7,
    agentName: 'Release Orchestrator',
    artifacts: [
      { id: 'art-4', name: 'error-log.json', type: 'log', size: 3400, createdAt: '2026-02-14T14:08:00Z' },
    ],
  },
  {
    id: 'run-4',
    cronjobId: 'cron-2',
    cronjobName: 'Weekly Content Digest',
    module: 'content',
    status: 'running',
    startedAt: '2026-02-21T09:00:00Z',
    actionsCount: 2,
    agentName: 'Content Strategist',
    artifacts: [],
  },
]

export const mockAuditEntries: AuditEntry[] = [
  { id: 'aud-1', action: 'Cronjob executed', actor: 'PR Triage Bot', module: 'projects', timestamp: '2026-02-21T02:12:00Z', details: 'Nightly PR Triage completed with 14 actions', severity: 'info' },
  { id: 'aud-2', action: 'Approval requested', actor: 'Finance Auditor', module: 'finance', timestamp: '2026-02-21T00:30:00Z', details: 'Recategorize 23 transactions pending review', severity: 'warning' },
  { id: 'aud-3', action: 'Agent error', actor: 'Expense Tracker', module: 'finance', timestamp: '2026-02-19T14:00:00Z', details: 'Plaid connection timeout after 3 retries', severity: 'error' },
  { id: 'aud-4', action: 'Training plan updated', actor: 'Training Coach', module: 'health', timestamp: '2026-02-21T07:03:00Z', details: 'Weekly plan adjusted based on recovery metrics', severity: 'info' },
  { id: 'aud-5', action: 'Content published', actor: 'Content Strategist', module: 'content', timestamp: '2026-02-20T10:00:00Z', details: 'Blog post "Scaling with AI" published to WordPress', severity: 'info' },
]

export const mockConnectors: Connector[] = [
  { id: 'conn-1', name: 'GitHub', category: 'VCS', icon: 'github', status: 'connected', description: 'Source code management and CI/CD', lastSync: '2026-02-21T11:00:00Z' },
  { id: 'conn-2', name: 'Slack', category: 'Communication', icon: 'message-square', status: 'connected', description: 'Team messaging and notifications', lastSync: '2026-02-21T10:55:00Z' },
  { id: 'conn-3', name: 'Google Calendar', category: 'Productivity', icon: 'calendar', status: 'connected', description: 'Calendar sync and scheduling', lastSync: '2026-02-21T10:00:00Z' },
  { id: 'conn-4', name: 'Plaid', category: 'Finance', icon: 'landmark', status: 'error', description: 'Bank account aggregation', lastSync: '2026-02-19T14:00:00Z' },
  { id: 'conn-5', name: 'WordPress', category: 'CMS', icon: 'globe', status: 'connected', description: 'Content management and publishing', lastSync: '2026-02-20T10:00:00Z' },
  { id: 'conn-6', name: 'Garmin', category: 'Health', icon: 'watch', status: 'connected', description: 'Fitness tracking and wearable data', lastSync: '2026-02-21T07:00:00Z' },
  { id: 'conn-7', name: 'Vercel', category: 'Deployment', icon: 'triangle', status: 'connected', description: 'Frontend deployment platform', lastSync: '2026-02-21T11:05:00Z' },
  { id: 'conn-8', name: 'QuickBooks', category: 'Finance', icon: 'receipt', status: 'disconnected', description: 'Accounting and invoicing', lastSync: undefined },
  { id: 'conn-9', name: 'Stripe', category: 'Billing', icon: 'credit-card', status: 'connected', description: 'Payment processing and billing', lastSync: '2026-02-21T09:30:00Z' },
  { id: 'conn-10', name: 'Google Analytics', category: 'Analytics', icon: 'bar-chart-3', status: 'connected', description: 'Web analytics and reporting', lastSync: '2026-02-21T08:00:00Z' },
]

export const mockTemplates: WorkflowTemplate[] = [
  { id: 'tmpl-1', name: 'PR Auto-Triage', description: 'Automatically label, assign, and prioritize incoming pull requests', module: 'projects', category: 'DevOps', rating: 4.8, usageCount: 2340, agents: ['PR Triage Bot'], tags: ['github', 'automation', 'ci-cd'] },
  { id: 'tmpl-2', name: 'Content Pipeline', description: 'End-to-end content creation from ideation to publishing', module: 'content', category: 'Marketing', rating: 4.6, usageCount: 1580, agents: ['Content Strategist'], tags: ['blog', 'seo', 'publishing'] },
  { id: 'tmpl-3', name: 'Monthly Close', description: 'Automated month-end financial reconciliation and reporting', module: 'finance', category: 'Accounting', rating: 4.9, usageCount: 890, agents: ['Finance Auditor'], tags: ['reconciliation', 'reporting', 'compliance'] },
  { id: 'tmpl-4', name: 'Training Periodization', description: 'AI-driven training plan with auto-adjustments based on recovery', module: 'health', category: 'Fitness', rating: 4.7, usageCount: 670, agents: ['Training Coach'], tags: ['training', 'recovery', 'wearables'] },
  { id: 'tmpl-5', name: 'Release Orchestration', description: 'Automated versioning, changelog generation, and deployment', module: 'projects', category: 'DevOps', rating: 4.5, usageCount: 1120, agents: ['Release Orchestrator'], tags: ['release', 'deployment', 'changelog'] },
  { id: 'tmpl-6', name: 'Expense Categorization', description: 'Auto-categorize and flag unusual transactions', module: 'finance', category: 'Accounting', rating: 4.3, usageCount: 450, agents: ['Expense Tracker'], tags: ['expenses', 'categorization', 'anomaly'] },
]

export const mockNotifications: Notification[] = [
  { id: 'notif-1', title: 'Approval Required', message: 'PR #1234 merge needs your review', type: 'warning', read: false, createdAt: '2026-02-21T02:15:00Z' },
  { id: 'notif-2', title: 'Run Completed', message: 'Nightly PR Triage finished successfully', type: 'success', read: false, createdAt: '2026-02-21T02:12:00Z' },
  { id: 'notif-3', title: 'Connector Error', message: 'Plaid connection failed after 3 retries', type: 'error', read: true, createdAt: '2026-02-19T14:00:00Z' },
  { id: 'notif-4', title: 'Training Updated', message: 'Weekly plan adjusted for recovery', type: 'info', read: false, createdAt: '2026-02-21T07:03:00Z' },
]

export const dashboardChartData = [
  { name: 'Mon', runs: 12, approvals: 3, errors: 1 },
  { name: 'Tue', runs: 18, approvals: 5, errors: 0 },
  { name: 'Wed', runs: 15, approvals: 4, errors: 2 },
  { name: 'Thu', runs: 22, approvals: 7, errors: 1 },
  { name: 'Fri', runs: 19, approvals: 6, errors: 0 },
  { name: 'Sat', runs: 8, approvals: 1, errors: 0 },
  { name: 'Sun', runs: 5, approvals: 0, errors: 0 },
]

export const moduleDistribution = [
  { name: 'Projects', value: 42, fill: '#FF7300' },
  { name: 'Content', value: 24, fill: '#B16FFF' },
  { name: 'Finance', value: 18, fill: '#3FC56B' },
  { name: 'Health', value: 16, fill: '#F59E0B' },
]
